"""
Django settings for inst_rsm project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from __future__ import unicode_literals
import environ
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INST_ROOT = environ.Path(__file__) - 1
ROOT = INST_ROOT - 1
ENV = environ.Env(DEBUG=(bool, False),) # set default values and casting

ENV.read_env(ROOT('.env'))
ENV.read_env(INST_ROOT('.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY',
                 default='ej@zm_lgexuud=owflr-5-(rw-h!484*f=^w96mx)7mkm_(e&n')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV('DEBUG')

ALLOWED_HOSTS = ['*']

# SECURITY WARNING: cookies sent in plain text on wire if HTTP_ONLY env var
# not set to True
CSRF_COOKIE_SECURE = ENV.bool('HTTPS_ONLY', default=False)
SESSION_COOKIE_SECURE = ENV.bool('HTTPS_ONLY', default=False)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',
                           'auth.backends.EmailModelBackend',)

# RSM API key, secret and url
SANDBOX_CLIENT_KEY = "FyQUivu3eR7lHwwPKjyX91G_XfUa"
SANDBOX_CLIENT_SECRET = "F69W5AR_npQl5VmNZty3jpxwgica"
PRODUCT_CLIENT_KEY = 'j6PRwp7ayh46nZ9JT7jQ2MAblfEa'
PRODUCT_CLIENT_SECRET = '5ZBkbhkaieDwORy5bo9fMTFCLJ8a'

DL_SANDBOX_URL = "https://sandbox.api.business.govt.nz/services/v1/radio-spectrum-management/DownloadLicences"
DL_PRODUCT_URL = "https://api.business.govt.nz/services/v1/radio-spectrum-management/DownloadLicences"

# Google Maps JavaScript API
GOOGLE_MAPS_API = "AIzaSyCh_1Wafny-plSdJF7lhtdMHpeLrOpEFNE"

# STRIPE public and secret keys
STRIPE_PUBLIC_KEY = ENV("STRIPE_PUBLIC_KEY", default="your test public key")
STRIPE_SECRET_KEY = ENV("STRIPE_SECRET_KEY", default="your test secret key")

# Application definition
# GIS_ENABLED = ENV.bool('GIS_ENABLED', default=True)

INSTALLED_APPS = (
    'dal',
    'dal_select2',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'debug_toolbar',
    'bootstrap3',
    'datetimewidget',

    'spectrum_db',
    'usermanagement',

    'djstripe',
)

SITE_ID = 1

# if GIS_ENABLED:
#     INSTALLED_APPS = tuple(list(INSTALLED_APPS)
#                            + ['django.contrib.gis',
#                               'rest_framework_gis',

#                               'assetanalytics.assetgeo',
#                               'assetanalytics.renewal.geo',
#                              ])

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'inst_rsm.urls'

WSGI_APPLICATION = 'inst_rsm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'rsm',
        'USER': 'rsm_user',
        'PASSWORD': 'rsm_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# if GIS_ENABLED:
#     DEFAULT_DB = 'spatialite'
# else:
# DEFAULT_DB = 'sqlite'

# DATABASES = {
#     'default': ENV.db(default='%s:///%s' % (DEFAULT_DB,
#                                             INST_ROOT('database.sqlite'))
#                      ),
# }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = ENV('STATIC_ROOT', default=ROOT('static'))

LOGIN_REDIRECT_URL = '/'

STATICFILES_DIRS = (
    INST_ROOT('static'),
    )

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [INST_ROOT('templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': ''
    }
INTERNAL_IPS = ['127.0.0.1', '::1', '0.0.0.0']

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# DEFAULT_FROM_EMAIL = 'appsupport@harmonic.co.nz'
# EMAIL_SUBJECT_PREFIX = ENV('EMAIL_SUBJECT_PREFIX', default='[ah-test] ')
# SERVER_EMAIL = ENV('SERVER_EMAIL', default='ah-test@unknown.local')
# INST_NAME = ENV('INST_NAME', default='inst_test_local')

# FAST_TESTS_ONLY = ENV.bool('FAST_TESTS_ONLY', default=False)

# DJ STRIPE SETTINGS
DJSTRIPE_CURRENCIES =(('nzd', 'NewZealand Dollars',), 
                      ('usd', 'U.S. Dollars',), 
                      ('gbp', 'Pounds (GBP)',), 
                      ('eur', 'Euros',))
